# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.3.0"
kotlinxDatetime = "0.7.1"
kotlinxSerializationCore = "1.10.0"
kotlinxCoroutines = "1.10.2"
kotest = "6.1.3"
detekt = "2.0.0-alpha.2"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
obor = { module = "net.orandja.obor:obor", version = "2.1.3" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotestProperty = { module = "io.kotest:kotest-property", version.ref = "kotest" }
detektGradlePlugin = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }

# Libraries can be bundled together for easier import
[bundles]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "dev.detekt", version.ref = "detekt" }